### ISSUE TITLE
https://github.com/utix-protocol/UtixSmartContracts/blob/develop/vulnerabilities.md

### ISSUE THREAD

**Issue by pkeane4osu** [utix-protocol/UtixSmartContracts#3]
Auditor

@pkeane4osu

Severity

Major

Description

I found this a short while ago just randomly looking at contract transactions being sent out on a large scale, what was found was the actual private keys for the addresses being sent tokens displayed once the transaction was confirmed. I copied the first small batch of the keys that were sent out in a large CanYa token distribution. Upon checking the keys, each one produced an address that was just sent various amounts of that specific token. From there ive kept this information private until now, however to detail the severity of this, I could literally sweep or send all funds from each and every address if I was a person looking to steal funds very very easily. 

Proposed Solution 

Simply put, quit blatantly sending the raw private keys to addresses being batch sent tokens. First suggestion immediately off the top of my head would be to implement a better Blind Signature Protocol that would encrypt the private keys. Then the keys would not be instantly available to anyone wanting to steal Crypto that was not intended for them to easily steal. Pretty basic but extremely needed at this point in time.

**Comment by utix-io** [comment]
We have investigated the issue, but were not able to reproduce the problem as we don't deal with private keys. None of it seems to be related to our project in fact.
